"""delete comment review

Revision ID: d62ecfb8ef59
Revises: 00ee80d538e5
Create Date: 2021-11-04 18:31:37.013782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62ecfb8ef59'
down_revision = '00ee80d538e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'reviewed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('reviewed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
